#!/usr/bin/env python3
"""Independently validate meshes generated by test_solid_junctions.js."""
from pathlib import Path
import json
import numpy as np
from shapely import contains_xy
from shapely.geometry import Polygon
from shapely.ops import unary_union
import trimesh

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / 'test-results' / 'solid-junctions'
summary = json.loads((OUT / 'summary.json').read_text(encoding='utf-8'))
results = []
for case in summary['results']:
    name = case['name']
    data = json.loads((OUT / f'{name}.json').read_text(encoding='utf-8'))
    mesh = trimesh.load(OUT / f'{name}.stl', force='mesh', process=True)
    assert mesh.is_watertight and mesh.is_winding_consistent, name
    assert mesh.body_count == 1, name
    assert mesh.volume > 0, name
    assert np.allclose(mesh.extents, [data['W'], data['H'], data['thickness']], atol=.0002), name
    cuts = unary_union([Polygon(r) for r in data['holes']])
    material = Polygon(data['outer']).difference(cuts)
    assert material.is_valid and material.geom_type == 'Polygon', name
    assert abs(material.area-data['area']) < max(.03, material.area*2e-5), name
    assert abs(mesh.volume-material.area*data['thickness']) < max(.03, mesh.volume*2e-5), name
    # Top/bottom triangles must never cover any interior of a through-cut.
    flat = np.abs(mesh.face_normals[:, 2]) > .99
    centers = mesh.triangles_center[flat]
    assert not contains_xy(cuts.buffer(-.0003), centers[:, 0], data['H']-centers[:, 1]).any(), name
    results.append({'name': name, 'watertight': True, 'components': 1, 'through_cuts': True})
result = {'passed': len(results), 'results': results}
(OUT / 'independent-validation.json').write_text(json.dumps(result, indent=2)+'\n', encoding='utf-8')
print(f"PASS: {len(results)} independently checked connected through-cut STL meshes.")
